"""Builds the demo duty passes and the page that hands them out, from agent/checkpoints.py.

Run from the repo root after changing a checkpoint, its scenario, or the on-duty employee below:

    uv run --with "qrcode[pil]" python frontend/design/render_passes.py

For every checkpoint it writes frontend/public/passes/<slug>.json (what the dashboard's scanner
reads) and <slug>-qr.png (a QR code of that JSON's URL), then frontend/public/passes/index.html,
the page served at https://raqeeb.khalid-ai.dev/passes where a scenario is picked and its code
shown, ready to hold up to the dashboard's camera.
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path

import qrcode

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from agent.checkpoints import CHECKPOINTS  # noqa: E402

PASSES = ROOT / "frontend" / "public" / "passes"
SITE = "https://raqeeb.khalid-ai.dev"

# The on-duty employee every demo pass carries. The dispatch call rings this number.
EMPLOYEE_NAME = "خالد آل دوسري"
EMPLOYEE_NUMBER = "0553225155"

LOGO = (
    '<svg viewBox="0 0 32 32" aria-hidden="true">'
    '<path d="M16 2.75 26.5 6.6v8.15c0 6.55-4.35 11.9-10.5 14.5-6.15-2.6-10.5-7.95-10.5-14.5V6.6z" fill="#f5f8ff"/>'
    '<path d="M8.75 16c1.9-3.1 4.3-4.65 7.25-4.65S21.35 12.9 23.25 16c-1.9 3.1-4.3 4.65-7.25 4.65S10.65 19.1 8.75 16z" '
    'fill="none" stroke="#0d2a61" stroke-width="1.7" stroke-linejoin="round"/>'
    '<circle cx="16" cy="16" r="2.3" fill="#0d2a61"/></svg>'
)


def write_pass(slug: str, location_name: str) -> None:
    payload = {"الموظف المناوب": EMPLOYEE_NAME, "رقم الموظف": EMPLOYEE_NUMBER, "الموقع": location_name}
    (PASSES / f"{slug}.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, box_size=16, border=4)
    qr.add_data(f"{SITE}/passes/{slug}.json")
    qr.make(fit=True)
    qr.make_image(fill_color="#0d2a61", back_color="white").save(PASSES / f"{slug}-qr.png")


def page() -> str:
    e = html.escape
    options, panels = [], []
    for index, checkpoint in enumerate(CHECKPOINTS):
        slug, name = checkpoint.pass_slug, checkpoint.name_ar
        headline = dict(checkpoint.scenario).get("الفعالية", "")
        selected = index == 0
        options.append(
            f'<button type="button" class="option" data-slug="{slug}" aria-pressed="{str(selected).lower()}">'
            f'<span class="option-name">{e(name)}</span><span class="option-line">{e(headline)}</span></button>'
        )
        details = "".join(f"<div><dt>{e(label)}</dt><dd>{e(detail)}</dd></div>" for label, detail in checkpoint.scenario)
        panels.append(
            f'<section class="panel" data-slug="{slug}" aria-label="{e(name)}"{"" if selected else " hidden"}>'
            f'<div class="code"><img src="./{slug}-qr.png" width="656" height="656" alt="رمز QR لبطاقة مناوبة {e(name)}" /></div>'
            f'<div class="pass">'
            f'<h2>{e(name)}</h2>'
            f'<dl class="facts">'
            f"<div><dt>الموظف المناوب</dt><dd>{e(EMPLOYEE_NAME)}</dd></div>"
            f'<div><dt>رقم الموظف</dt><dd dir="ltr">{e(EMPLOYEE_NUMBER)}</dd></div>'
            f"</dl>"
            f'<h3>تفاصيل السيناريو</h3><dl class="details">{details}</dl>'
            f'<a class="link" href="./{slug}.json">محتوى البطاقة</a>'
            f"</div></section>"
        )

    return f"""<!doctype html>
<!-- Generated by frontend/design/render_passes.py from agent/checkpoints.py. Do not edit by hand. -->
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>رقيب · بطاقات المناوبة التجريبية</title>
<meta name="description" content="اختر سيناريو واعرض رمز بطاقة المناوبة، ثم امسحه بكاميرا لوحة رقيب لبدء العرض." />
<meta name="theme-color" content="#0d2a61" />
<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
<style>
@font-face {{ font-family: "Thmanyah Sans"; font-weight: 400; font-display: swap; src: url("https://cdn.jsdelivr.net/gh/khaliddosari/thmanyah-fonts@v1/thmanyah%20typeface/thmanyahsans/woff2/thmanyahsans-Regular.woff2") format("woff2"); }}
@font-face {{ font-family: "Thmanyah Sans"; font-weight: 700; font-display: swap; src: url("https://cdn.jsdelivr.net/gh/khaliddosari/thmanyah-fonts@v1/thmanyah%20typeface/thmanyahsans/woff2/thmanyahsans-Bold.woff2") format("woff2"); }}
@font-face {{ font-family: "Thmanyah Serif Display"; font-weight: 900; font-display: swap; src: url("https://cdn.jsdelivr.net/gh/khaliddosari/thmanyah-fonts@v1/thmanyah%20typeface/thmanyahserifdisplay/woff2/thmanyahserifdisplay-Black.woff2") format("woff2"); }}
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; }}
/* a solid navy base under the gradient, so a long page on a phone never scrolls onto white */
html {{ background: #0a1f4a; }}
body {{
  min-height: 100dvh; color: #fff; font-family: "Thmanyah Sans", system-ui, sans-serif; font-size: 16px;
  background: radial-gradient(900px 600px at 15% 0%, rgba(88,140,255,.28), transparent 60%), linear-gradient(200deg, #06132c, #0d2a61 40%, #0a1f4a);
}}
.wrap {{ max-width: 1120px; margin: 0 auto; padding: 24px 16px 40px; }}
header {{ display: flex; align-items: center; gap: 12px; }}
header svg {{ width: 44px; height: 44px; flex: none; }}
.brand {{ font-family: "Thmanyah Serif Display", serif; font-weight: 900; font-size: 34px; line-height: 1; }}
h1 {{ margin: 18px 0 6px; font-size: 26px; line-height: 1.35; }}
.lead {{ margin: 0; color: #c8d5f6; line-height: 1.7; }}
.layout {{ margin-top: 22px; display: grid; gap: 18px; }}
.options {{ display: flex; gap: 10px; overflow-x: auto; padding-bottom: 4px; scroll-snap-type: x mandatory; }}
.option {{
  flex: 0 0 auto; scroll-snap-align: start; min-height: 48px; max-width: 250px; padding: 10px 16px; text-align: start; cursor: pointer;
  font: inherit; color: #e6ecfb; background: rgba(255,255,255,.07); border: 1.5px solid rgba(255,255,255,.2); border-radius: 16px;
  display: flex; flex-direction: column; gap: 2px;
}}
.option:hover {{ background: rgba(255,255,255,.12); }}
.option:focus-visible {{ outline: 3px solid #a9c1ff; outline-offset: 2px; }}
.option[aria-pressed="true"] {{ background: #f5f8ff; color: #0d2a61; border-color: #f5f8ff; }}
.option-name {{ font-weight: 700; }}
.option-line {{ font-size: 13px; opacity: .8; display: none; }}
.panel {{ display: grid; gap: 18px; }}
.panel[hidden] {{ display: none; }}
.code {{ background: #fff; border-radius: 22px; padding: 10px; box-shadow: 0 24px 60px -24px rgba(0,0,0,.6); }}
.code img {{ display: block; width: 100%; height: auto; image-rendering: pixelated; }}
.pass {{ background: rgba(255,255,255,.08); border: 1.5px solid rgba(255,255,255,.18); border-radius: 22px; padding: 18px; }}
h2 {{ margin: 0 0 12px; font-size: 24px; }}
h3 {{ margin: 18px 0 8px; font-size: 16px; color: #a9c1ff; }}
dl {{ margin: 0; }}
dt {{ color: #a9c1ff; font-size: 13px; }}
dd {{ margin: 0; line-height: 1.6; }}
.facts {{ display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }}
.facts dd {{ font-weight: 700; }}
.details {{ display: grid; gap: 8px; }}
.link {{ display: inline-block; margin-top: 16px; color: #a9c1ff; font-size: 14px; }}
.open {{ display: inline-flex; margin-top: 18px; min-height: 48px; align-items: center; padding: 0 22px; border-radius: 999px; background: #f5f8ff; color: #0d2a61; font-weight: 700; text-decoration: none; }}
@media (min-width: 900px) {{
  .wrap {{ padding-top: 40px; }}
  .layout {{ grid-template-columns: 300px minmax(0, 1fr); align-items: start; }}
  .options {{ flex-direction: column; overflow: visible; }}
  .option {{ max-width: none; }}
  .option-line {{ display: block; }}
  .panel {{ grid-template-columns: minmax(0, 420px) minmax(0, 1fr); align-items: start; }}
}}
</style>
</head>
<body>
<div class="wrap">
  <header>{LOGO}<span class="brand">رقيب</span></header>
  <main>
  <h1>بطاقات المناوبة التجريبية</h1>
  <p class="lead">اختر سيناريو، ثم افتح لوحة رقيب على جهاز آخر وهي في وضع «مسح البطاقة»، ووجّه الرمز نحو الكاميرا. تُملأ بيانات المناوبة والموقع تلقائيًا، ويُرفق السيناريو بالبلاغ وبمكالمة الإبلاغ.</p>
  <div class="layout">
    <div class="options" role="group" aria-label="السيناريوهات">{"".join(options)}</div>
    <div>{"".join(panels)}</div>
  </div>
  <a class="open" href="/">فتح لوحة رقيب</a>
  </main>
</div>
<script>
  // Picking a scenario shows its pass; the choice is kept in the address, so /passes#fii opens on it.
  const options = [...document.querySelectorAll(".option")];
  const panels = [...document.querySelectorAll(".panel")];
  function show(slug, focus) {{
    if (!panels.some((p) => p.dataset.slug === slug)) slug = panels[0].dataset.slug;
    options.forEach((o) => o.setAttribute("aria-pressed", String(o.dataset.slug === slug)));
    panels.forEach((p) => (p.hidden = p.dataset.slug !== slug));
    // on a phone the options scroll sideways; keep the chosen one in view
    options.find((o) => o.dataset.slug === slug)?.scrollIntoView({{ block: "nearest", inline: "nearest" }});
    if (focus) history.replaceState(null, "", "#" + slug);
  }}
  options.forEach((o) => o.addEventListener("click", () => show(o.dataset.slug, true)));
  show(location.hash.slice(1), false);
</script>
</body>
</html>
"""


PASSES.mkdir(parents=True, exist_ok=True)
for checkpoint in CHECKPOINTS:
    write_pass(checkpoint.pass_slug, checkpoint.name_ar)
(PASSES / "index.html").write_text(page(), encoding="utf-8")
print(f"wrote {len(CHECKPOINTS)} passes and passes/index.html to {PASSES}")
