// Mirrors agent/intake.py, whose checkpoints and scenarios live in agent/checkpoints.py. The backend
// is the gate and refuses anything else; these copies only let the form say so before a request is sent.
//
// A visitor never handles a phone number: their dispatch conversation happens in their own
// browser. A signed-in dashboard does, so the number it prefills can be edited for a run, and
// this says early what the backend would say anyway.

export const CHECKPOINT_LOCATIONS = [
  "Private Aviation Terminal",
  "LEAP 2026 Exhibition",
  "Future Investment Initiative",
  "Saudi Falcons and Hunting Exhibition",
  "Money20/20 Middle East",
  "Black Hat MEA",
] as const

export type CheckpointLocation = (typeof CHECKPOINT_LOCATIONS)[number]

// The demo pass published for each checkpoint under /passes, generated by
// frontend/design/render_passes.py from agent/checkpoints.py. Change them together.
export const PASS_SLUGS: Record<CheckpointLocation, string> = {
  "Private Aviation Terminal": "private-aviation",
  "LEAP 2026 Exhibition": "leap-2026",
  "Future Investment Initiative": "fii",
  "Saudi Falcons and Hunting Exhibition": "falcons",
  "Money20/20 Middle East": "money2020",
  "Black Hat MEA": "blackhat",
}

const SAUDI_MOBILE = /^(?:\+?966|0)?(5\d{8})$/

/** +9665XXXXXXXX for any common way of writing a Saudi mobile, otherwise null. */
export function normalizeSaudiMobile(raw: string): string | null {
  const match = SAUDI_MOBILE.exec(raw.replace(/[\s\-()]/g, ""))
  return match ? `+966${match[1]}` : null
}
