// Mirrors agent/intake.py, whose checkpoints and scenarios live in agent/checkpoints.py. The backend
// is the gate and refuses anything else; these copies only let the form say so before a request is sent.
//
// No phone number validation lives here any more: the dashboard never handles one. The mobile a
// dispatch call rings is configured on the server (see agent/employees.py), and a visitor's
// dispatch conversation happens in their own browser instead.

export const CHECKPOINT_LOCATIONS = [
  "Private Aviation Terminal",
  "LEAP 2026 Exhibition",
  "Future Investment Initiative",
  "Saudi Falcons and Hunting Exhibition",
  "Money20/20 Middle East",
  "Black Hat MEA",
] as const

export type CheckpointLocation = (typeof CHECKPOINT_LOCATIONS)[number]

// The demo pass published for each checkpoint under /passes, generated by
// frontend/design/render_passes.py from agent/checkpoints.py. Change them together.
export const PASS_SLUGS: Record<CheckpointLocation, string> = {
  "Private Aviation Terminal": "private-aviation",
  "LEAP 2026 Exhibition": "leap-2026",
  "Future Investment Initiative": "fii",
  "Saudi Falcons and Hunting Exhibition": "falcons",
  "Money20/20 Middle East": "money2020",
  "Black Hat MEA": "blackhat",
}
